// KOSPI200 (일부 샘플)
const KOSPI200 = [
    { name: "삼성전자", ticker: "005930.KS" },
    { name: "SK하이닉스", ticker: "000660.KS" },
    { name: "현대차", ticker: "005380.KS" },
    { name: "LG에너지솔루션", ticker: "373220.KS" },
    { name: "NAVER", ticker: "035420.KS" },
    { name: "카카오", ticker: "035720.KS" }
];

// S&P500 (일부 샘플)
const SP500 = [
  { name: "Apple Inc.", ticker: "AAPL" },
  { name: "Microsoft Corporation", ticker: "MSFT" },
  { name: "Amazon.com Inc.", ticker: "AMZN" },
  { name: "Alphabet Inc. Class A", ticker: "GOOGL" },
  { name: "Alphabet Inc. Class C", ticker: "GOOG" },
  { name: "NVIDIA Corporation", ticker: "NVDA" },
  { name: "Meta Platforms Inc.", ticker: "META" },
  { name: "Berkshire Hathaway Inc.", ticker: "BRK.B" },
  { name: "Tesla Inc.", ticker: "TSLA" },
  { name: "Eli Lilly and Company", ticker: "LLY" },

  { name: "JPMorgan Chase & Co.", ticker: "JPM" },
  { name: "Visa Inc.", ticker: "V" },
  { name: "UnitedHealth Group Inc.", ticker: "UNH" },
  { name: "Mastercard Incorporated", ticker: "MA" },
  { name: "Johnson & Johnson", ticker: "JNJ" },
  { name: "Exxon Mobil Corporation", ticker: "XOM" },
  { name: "Procter & Gamble Company", ticker: "PG" },
  { name: "Home Depot Inc.", ticker: "HD" },
  { name: "Chevron Corporation", ticker: "CVX" },
  { name: "AbbVie Inc.", ticker: "ABBV" },

  { name: "Broadcom Inc.", ticker: "AVGO" },
  { name: "Costco Wholesale Corporation", ticker: "COST" },
  { name: "Merck & Co. Inc.", ticker: "MRK" },
  { name: "PepsiCo Inc.", ticker: "PEP" },
  { name: "Coca-Cola Company", ticker: "KO" },
  { name: "Walmart Inc.", ticker: "WMT" },
  { name: "Adobe Inc.", ticker: "ADBE" },
  { name: "Cisco Systems Inc.", ticker: "CSCO" },
  { name: "Salesforce Inc.", ticker: "CRM" },
  { name: "Netflix Inc.", ticker: "NFLX" },

  { name: "Oracle Corporation", ticker: "ORCL" },
  { name: "Accenture plc", ticker: "ACN" },
  { name: "Texas Instruments Incorporated", ticker: "TXN" },
  { name: "Advanced Micro Devices Inc.", ticker: "AMD" },
  { name: "Intel Corporation", ticker: "INTC" },
  { name: "QUALCOMM Incorporated", ticker: "QCOM" },
  { name: "IBM Corporation", ticker: "IBM" },
  { name: "ServiceNow Inc.", ticker: "NOW" },
  { name: "Micron Technology Inc.", ticker: "MU" },
  { name: "Applied Materials Inc.", ticker: "AMAT" },

  { name: "Bank of America Corporation", ticker: "BAC" },
  { name: "Wells Fargo & Company", ticker: "WFC" },
  { name: "Morgan Stanley", ticker: "MS" },
  { name: "Goldman Sachs Group Inc.", ticker: "GS" },
  { name: "Citigroup Inc.", ticker: "C" },
  { name: "American Express Company", ticker: "AXP" },
  { name: "BlackRock Inc.", ticker: "BLK" },
  { name: "Charles Schwab Corporation", ticker: "SCHW" },
  { name: "S&P Global Inc.", ticker: "SPGI" },
  { name: "CME Group Inc.", ticker: "CME" },

  { name: "Pfizer Inc.", ticker: "PFE" },
  { name: "Thermo Fisher Scientific Inc.", ticker: "TMO" },
  { name: "Danaher Corporation", ticker: "DHR" },
  { name: "Bristol-Myers Squibb Company", ticker: "BMY" },
  { name: "Abbott Laboratories", ticker: "ABT" },
  { name: "Medtronic plc", ticker: "MDT" },
  { name: "Intuitive Surgical Inc.", ticker: "ISRG" },
  { name: "Eli Lilly and Company", ticker: "LLY" },
  { name: "Gilead Sciences Inc.", ticker: "GILD" },
  { name: "Moderna Inc.", ticker: "MRNA" },

  { name: "Walt Disney Company", ticker: "DIS" },
  { name: "Comcast Corporation", ticker: "CMCSA" },
  { name: "Charter Communications Inc.", ticker: "CHTR" },
  { name: "Warner Bros. Discovery Inc.", ticker: "WBD" },
  { name: "Netflix Inc.", ticker: "NFLX" },
  { name: "Meta Platforms Inc.", ticker: "META" },
  { name: "Alphabet Inc. Class A", ticker: "GOOGL" },
  { name: "Snap-on Incorporated", ticker: "SNA" },
  { name: "Electronic Arts Inc.", ticker: "EA" },
  { name: "Take-Two Interactive Software Inc.", ticker: "TTWO" },

  { name: "NIKE Inc.", ticker: "NKE" },
  { name: "Starbucks Corporation", ticker: "SBUX" },
  { name: "McDonald's Corporation", ticker: "MCD" },
  { name: "Yum! Brands Inc.", ticker: "YUM" },
  { name: "Target Corporation", ticker: "TGT" },
  { name: "Lowe's Companies Inc.", ticker: "LOW" },
  { name: "TJX Companies Inc.", ticker: "TJX" },
  { name: "Marriott International Inc.", ticker: "MAR" },
  { name: "Hilton Worldwide Holdings Inc.", ticker: "HLT" },
  { name: "Booking Holdings Inc.", ticker: "BKNG" },

  { name: "Union Pacific Corporation", ticker: "UNP" },
  { name: "United Parcel Service Inc.", ticker: "UPS" },
  { name: "FedEx Corporation", ticker: "FDX" },
  { name: "Deere & Company", ticker: "DE" },
  { name: "Caterpillar Inc.", ticker: "CAT" },
  { name: "General Electric Company", ticker: "GE" },
  { name: "3M Company", ticker: "MMM" },
  { name: "Honeywell International Inc.", ticker: "HON" },
  { name: "Lockheed Martin Corporation", ticker: "LMT" },
  { name: "Raytheon Technologies Corporation", ticker: "RTX" },

  { name: "NextEra Energy Inc.", ticker: "NEE" },
  { name: "Duke Energy Corporation", ticker: "DUK" },
  { name: "Southern Company", ticker: "SO" },
  { name: "Dominion Energy Inc.", ticker: "D" },
  { name: "American Electric Power Company", ticker: "AEP" },
  { name: "Exelon Corporation", ticker: "EXC" },
  { name: "Waste Management Inc.", ticker: "WM" },
  { name: "Republic Services Inc.", ticker: "RSG" },
  { name: "Verizon Communications Inc.", ticker: "VZ" },
  { name: "AT&T Inc.", ticker: "T" }
];

